const wordList = [
  { word: "tree", hint: "Essential for Christmas decor in homes" },
  { word: "snowman", hint: "Built from snow, with a carrot nose" },
  { word: "santa", hint: "Jolly man who delivers gifts" },
  { word: "reindeer", hint: "Pulls Santa’s sleigh" },
  { word: "stocking", hint: "Hung by the fireplace for gifts" },
  { word: "sleigh", hint: "Santa's vehicle for delivering gifts" },
  { word: "gifts", hint: "Presents given at Christmas" },
  { word: "ornaments", hint: "Decorations on the Christmas tree" },
  { word: "tinsel", hint: "Shiny decoration for the tree" },
  { word: "carols", hint: "Songs sung during the holiday season" },
  { word: "mistletoe", hint: "You kiss under this during Christmas" },
  { word: "wreath", hint: "Circular decoration made of branches" },
  { word: "cookies", hint: "Left out for Santa" },
  { word: "eggnog", hint: "A holiday drink, often spiced" },
  { word: "gingerbread", hint: "Sweet cookies shaped like people or houses" },
  { word: "snowflakes", hint: "Unique shapes that fall from the sky" },
  { word: "chimney", hint: "Where Santa enters to deliver presents" },
  { word: "elves", hint: "Santa’s helpers in the North Pole" },
  { word: "yule", hint: "Another term for Christmas" },
  { word: "holly", hint: "A plant with red berries used for decorations" },
  { word: "frosty", hint: "Famous snowman with a top hat" },
  { word: "icicles", hint: "Frozen water hanging from roofs" },
  { word: "socks", hint: "Warm footwear worn in winter" },
  { word: "fireplace", hint: "Where stockings are hung" },
  { word: "nutcracker", hint: "A toy that cracks nuts, also a ballet" },
  { word: "blizzard", hint: "A severe snowstorm with strong winds" },
  { word: "candles", hint: "Used to light the home and tree" },
  { word: "hearth", hint: "The floor of a fireplace" },
  { word: "poinsettia", hint: "A red plant often used in Christmas decorations" },
  { word: "feliz", hint: "Spanish word for Merry, as in 'Feliz Navidad'" },
  { word: "toys", hint: "Things children receive for Christmas" },
  { word: "north pole", hint: "Santa’s home" },
  { word: "jingle", hint: "The sound of bells during Christmas" },
  { word: "presents", hint: "Wrapped items given on Christmas Day" },
  { word: "yulelog", hint: "A traditional Christmas dessert" },
  { word: "snowball", hint: "A frozen ball of snow, often thrown in play" },
  { word: "candlelight", hint: "Soft light from burning candles" },
  { word: "carolers", hint: "People who sing songs at Christmas" },
  { word: "winter", hint: "The cold season" },
  { word: "frost", hint: "Ice that forms on windows" },
  { word: "flakes", hint: "Tiny pieces of snow" },
  { word: "hot cocoa", hint: "A warm chocolate drink, often with marshmallows" },
  { word: "jolly", hint: "Happy and full of cheer" },
  { word: "snowstorm", hint: "A heavy snowfall" },
  { word: "chilly", hint: "A cold temperature" },
  { word: "toboggan", hint: "A sled used for sliding down hills" },
  { word: "sled", hint: "A vehicle used to slide on snow" },
  { word: "skates", hint: "Worn on your feet to glide on ice" },
  { word: "mittens", hint: "Worn on hands to keep them warm" },
  { word: "scarf", hint: "Worn around the neck for warmth" },
  { word: "snowplow", hint: "A vehicle that clears snow from roads" },
  { word: "icicle", hint: "Frozen water that forms in pointed shapes" },
  { word: "snowball", hint: "Formed by packing snow into a ball" },
  { word: "crisp", hint: "A description of cold air in winter" },
  { word: "evergreen", hint: "A tree that stays green year-round" },
  { word: "fleece", hint: "Warm material often used for winter jackets" },
  { word: "chill", hint: "A cold sensation" },
  { word: "snowshoe", hint: "Footwear designed for walking on snow" },
  { word: "hibernation", hint: "Animals sleep through winter" },
  { word: "solstice", hint: "The shortest day of the year, in winter" },
  { word: "shiver", hint: "To shake because of the cold" },
  { word: "blitzen", hint: "One of Santa’s reindeer" },
  { word: "comet", hint: "One of Santa's reindeer" },
  { word: "vixen", hint: "One of Santa’s reindeer" },
  { word: "cupid", hint: "One of Santa’s reindeer" },
  { word: "donner", hint: "One of Santa’s reindeer" },
  { word: "dancer", hint: "One of Santa’s reindeer" },
  { word: "prancer", hint: "One of Santa’s reindeer" },
  { word: "rudolph", hint: "The red-nosed reindeer" },
  { word: "sparks", hint: "Tiny glowing particles from a fire" },
  { word: "tinsels", hint: "Thin shiny strands used to decorate" },
  { word: "snowdrift", hint: "A large pile of snow" },
  { word: "blizzard", hint: "Heavy snow and wind together" },
  { word: "glistening", hint: "Shining and sparkling" },
  { word: "cozy", hint: "Warm and comfortable, often used to describe a home" },
  { word: "wool", hint: "A warm material from sheep" },
  { word: "icicles", hint: "Frozen water hanging from eaves" },
  { word: "jack frost", hint: "The personification of winter chill" }
];
